Repository chef/chef-analyze, pull requests merged in 2019-12, with the labels that each got.

#91 add:(flag) new --only-unused for cookbooks report
  cmd/report.go
  pkg/formatter/formatter.go
  pkg/reporting/cookbooks.go
  pkg/reporting/cookbooks_test.go
Labels: Aspect: UI, Aspect: UX, Status: Adopted, Triage: Confirmed, Type: Enhancement

#96 Scope buildkite badge to master only
  README.md
Labels: Expeditor: Skip All

#114 save-reports:(fix) avoid saving empty reports
  cmd/report.go
Labels: Aspect: Correctness, Expeditor: Skip Code Coverage, Status: Adopted, Type: Bug

#110 Consistency on report commands
  cmd/report.go
  pkg/formatter/csv.go
  pkg/formatter/formatter.go
  pkg/formatter/table.go
  pkg/formatter/table_test.go
  pkg/formatter/txt.go
  pkg/reporting/cookbooks.go
  pkg/reporting/cookbooks_test.go
Labels: Aspect: UX, Priority: Medium, Status: Adopted, Triage: Confirmed, Type: Enhancement

#115 integration:(fix-test) catch errors on buildkite
  .expeditor/verify.pipeline.yml
  integration/credentials_test.go
  integration/framework_test.go
  scripts/integration_tests.ps1
Labels: Expeditor: Skip Code Coverage

#124 move .analyze-cache/ to $HOME/.chef-workstation
  .gitignore
  Makefile
  cmd/report.go
  go.mod
  go.sum
  pkg/reporting/cookbooks.go
  pkg/reporting/cookbooks_test.go
  vendor/github.com/chef/go-libs/config/finder.go
  vendor/github.com/chef/go-libs/config/workstation.go
  vendor/github.com/spf13/viper/.gitignore
  vendor/github.com/spf13/viper/.golangci.yml
  vendor/github.com/spf13/viper/Makefile
  vendor/github.com/spf13/viper/README.md
  vendor/github.com/spf13/viper/go.mod
  vendor/github.com/spf13/viper/go.sum
  vendor/github.com/spf13/viper/util.go
  vendor/github.com/spf13/viper/viper.go
  vendor/gopkg.in/ini.v1/.gitignore
  vendor/gopkg.in/ini.v1/.travis.yml
  vendor/gopkg.in/ini.v1/LICENSE
  vendor/gopkg.in/ini.v1/Makefile
  vendor/gopkg.in/ini.v1/README.md
  vendor/gopkg.in/ini.v1/data_source.go
  vendor/gopkg.in/ini.v1/deprecated.go
  vendor/gopkg.in/ini.v1/error.go
  vendor/gopkg.in/ini.v1/file.go
  vendor/gopkg.in/ini.v1/helper.go
  vendor/gopkg.in/ini.v1/ini.go
  vendor/gopkg.in/ini.v1/key.go
  vendor/gopkg.in/ini.v1/parser.go
  vendor/gopkg.in/ini.v1/section.go
  vendor/gopkg.in/ini.v1/struct.go
  vendor/modules.txt
Labels: Status: Adopted, Triage: Confirmed, Type: Enhancement

#127 Tidying up old Golang dependencies
  go.sum
Labels: Expeditor: Skip Code Coverage

#129 unit:(tests) mock home dir as temp dir
  pkg/reporting/chef_client_test.go
  pkg/reporting/client_test.go
  pkg/reporting/cookbooks_test.go
  pkg/reporting/cookstyle_test.go
  pkg/reporting/reporting_test.go
  pkg/reporting/setup_test.go
Labels: Aspect: Stability, Priority: Low, Status: Adopted, Triage: Confirmed, Type: Chore, Type: Tech Debt

#134 hab:(exe) build packages for Windows
  .bldr.toml
  habitat/plan.ps1
  habitat/plan.sh
  scripts/integration_tests.ps1
Labels: Expeditor: Skip Code Coverage, Status: Adopted, Triage: Confirmed, Type: Enhancement

#132 s3_session:(win) display windows env variables
  cmd/s3_utils.go
Labels: Expeditor: Skip Code Coverage, Platform: AWS, Status: Adopted, Triage: Confirmed, Type: Chore

#130 studio:(enhancement) update deps and enable Go helpers
  .gitignore
  .studiorc
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/request/retryer.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/service/s3/api.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload_input.go
  vendor/github.com/spf13/cast/.travis.yml
  vendor/github.com/spf13/cast/Makefile
  vendor/github.com/spf13/cast/caste.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: Expeditor: Skip All, Status: Adopted, Triage: Confirmed, Type: Chore
