Repository chef/chef-analyze, pull requests merged in 2019-11, with the labels that each got.

#40 Adds Apache License 2.0
  LICENSE
  cmd/config.go
  cmd/errors.go
  cmd/report.go
  cmd/root.go
  integration/framework_test.go
  integration/help_test.go
  main.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/errors.go
  pkg/reporting/chef_client.go
  pkg/reporting/cookbooks.go
  pkg/reporting/nodes.go
Labels: Expeditor: Skip All, Type: Chore

#45 Display code coverage message for 0% increase
  .buildkite/hooks/post-artifact
  .expeditor/config.yml
Labels: Aspect: Testing, Expeditor: Skip Code Coverage, Type: Chore

#51 Fix unbound variable at .expeditor/update_converge
  .expeditor/update_coverage.sh
Labels: Expeditor: Skip Version Bump, Type: Chore

#50 Add --no-ssl-check global flag
  cmd/report.go
  cmd/root.go
  pkg/config/config.go
  pkg/reporting/chef_client.go
  pkg/reporting/chef_client_test.go
  pkg/reporting/nodes_test.go
Labels: Aspect: Security, Status: Adopted, Triage: Confirmed, Type: Enhancement

#39 [featflag] Go package
  pkg/featflag/features.go
  pkg/featflag/features_test.go
Labels: Triage: Feature Request, Type: Design Proposal

#54 [pipeline] Shrink Code Coverage Table (GH Comment)
  .buildkite/hooks/post-artifact
Labels: Expeditor: Skip All, Type: Chore

#52 Adds docs/REALISTIC-TEST-ENV.md
  Makefile
  README.md
  docs/DESIGN.md
  docs/REALISTIC-TEST-ENV.md
Labels: Aspect: Documentation, Aspect: Testing, Expeditor: Skip All, Status: Adopted, Type: Chore

#55 Add cookbook version data to node report
  cmd/report.go
  go.mod
  go.sum
  pkg/reporting/cookbooks_test.go
  pkg/reporting/nodes.go
  pkg/reporting/nodes_test.go
  pkg/reporting/reporting_test.go
  vendor/github.com/mattn/go-runewidth/.travis.yml
  vendor/github.com/mattn/go-runewidth/LICENSE
  vendor/github.com/mattn/go-runewidth/README.mkd
  vendor/github.com/mattn/go-runewidth/go.mod
  vendor/github.com/mattn/go-runewidth/runewidth.go
  vendor/github.com/mattn/go-runewidth/runewidth_appengine.go
  vendor/github.com/mattn/go-runewidth/runewidth_js.go
  vendor/github.com/mattn/go-runewidth/runewidth_posix.go
  vendor/github.com/mattn/go-runewidth/runewidth_table.go
  vendor/github.com/mattn/go-runewidth/runewidth_windows.go
  vendor/github.com/olekukonko/tablewriter/.gitignore
  vendor/github.com/olekukonko/tablewriter/.travis.yml
  vendor/github.com/olekukonko/tablewriter/LICENSE.md
  vendor/github.com/olekukonko/tablewriter/README.md
  vendor/github.com/olekukonko/tablewriter/csv.go
  vendor/github.com/olekukonko/tablewriter/go.mod
  vendor/github.com/olekukonko/tablewriter/go.sum
  vendor/github.com/olekukonko/tablewriter/table.go
  vendor/github.com/olekukonko/tablewriter/table_with_color.go
  vendor/github.com/olekukonko/tablewriter/util.go
  vendor/github.com/olekukonko/tablewriter/wrap.go
  vendor/github.com/spf13/viper/.travis.yml
  vendor/github.com/spf13/viper/README.md
  vendor/github.com/spf13/viper/flags.go
  vendor/github.com/spf13/viper/go.mod
  vendor/github.com/spf13/viper/go.sum
  vendor/github.com/spf13/viper/viper.go
  vendor/github.com/subosito/gotenv/.env
  vendor/github.com/subosito/gotenv/.env.invalid
  vendor/github.com/subosito/gotenv/.gitignore
  vendor/github.com/subosito/gotenv/.travis.yml
  vendor/github.com/subosito/gotenv/CHANGELOG.md
  vendor/github.com/subosito/gotenv/LICENSE
  vendor/github.com/subosito/gotenv/README.md
  vendor/github.com/subosito/gotenv/appveyor.yml
  vendor/github.com/subosito/gotenv/gotenv.go
  vendor/golang.org/x/sys/unix/fdset.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/modules.txt
Labels: Aspect: UI, Aspect: UX, Status: Adopted, Triage: Confirmed, Triage: Feature Request, Type: Enhancement

#62 Adds GH issue templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/BUG_TEMPLATE.md
  .github/ISSUE_TEMPLATE/DESIGN_PROPOSAL.md
  .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
Labels: Aspect: Documentation, Aspect: Integration, Expeditor: Skip All, Type: Chore

#61 Updates project status + corrects trademark
  README.md
  cmd/report.go
  cmd/root.go
  docs/DESIGN.md
Labels: Aspect: Documentation, Expeditor: Skip Code Coverage, Type: Chore

#64 Fix Habitat builds
  Makefile
Labels: Aspect: Packaging, Expeditor: Skip Code Coverage, Type: Bug

#65 Pass CI=true to habitat build pipeline
  .expeditor/build.habitat.yml
Labels: Aspect: Packaging, Expeditor: Skip Code Coverage, Type: Bug

#68 Make go-build the default make tasks
  Makefile
  README.md
Labels: Expeditor: Skip Code Coverage, Type: Chore

#70 Install git for downloading go deps
  .studiorc
Labels: Expeditor: Skip All

#58 Integrate Config with Feature Flags library
  pkg/featflag/features.go
  pkg/featflag/features_test.go
  pkg/featflag/lookup.go
  pkg/featflag/lookup_test.go
Labels: Aspect: Integration, Aspect: Portability, Status: Adopted, Triage: Confirmed, Type: Design Proposal, Type: Enhancement

#72 Read and Merge WS Tray App config
  .studiorc
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/errors.go
  pkg/config/finder.go
  pkg/config/finder_test.go
  pkg/featflag/example/main.go
  pkg/featflag/features.go
  pkg/featflag/features_test.go
Labels: Aspect: Portability, Status: Adopted, Triage: Confirmed, Type: Enhancement

#73 Remove config, credentials and featflag pkgs
  cmd/report.go
  cmd/root.go
  go.mod
  go.sum
  pkg/config/config_test.go
  pkg/config/finder_test.go
  pkg/credentials/credentials_test.go
  pkg/featflag/example/main.go
  pkg/featflag/features.go
  pkg/featflag/features_test.go
  pkg/featflag/lookup.go
  pkg/featflag/lookup_test.go
  pkg/reporting/nodes_test.go
  pkg/reporting/reporting.go
  vendor/github.com/chef/go-libs/LICENSE
  vendor/github.com/chef/go-libs/config/config.go
  vendor/github.com/chef/go-libs/config/errors.go
  vendor/github.com/chef/go-libs/config/finder.go
  vendor/github.com/chef/go-libs/credentials/credentials.go
  vendor/github.com/chef/go-libs/credentials/errors.go
  vendor/modules.txt
Labels: Status: Adopted, Triage: Confirmed, Type: Chore

#74 chef-analyze is in development and will be hidden
  go.mod
  go.sum
  integration/featflag_test.go
  integration/framework_test.go
  main.go
  vendor/github.com/chef/go-libs/featflag/features.go
  vendor/github.com/chef/go-libs/featflag/lookup.go
  vendor/modules.txt
Labels: Aspect: Security, Aspect: UX, Status: Adopted, Triage: Confirmed, Type: Breaking Change, Type: Enhancement

#78 Update REALISTIC-TEST-ENV.md
  docs/REALISTIC-TEST-ENV.md
Labels: Expeditor: Skip All
