Repository chef/chef-analyze, pull requests merged in 2020-02, with the labels that each got.

#158 (design doc): upgrade suggestions
  docs/Upgrade_Suggestions_Data_Analysis.md
Labels: Expeditor: Skip Code Coverage, Status: Adopted, Triage: Confirmed, Type: Design Proposal

#176 Increase coverage: add test for filter footer in report
  pkg/formatter/table_test.go
Labels: Type: Chore

#175 Implements sorting on cookbooks report #98
  pkg/formatter/csv.go
  pkg/formatter/csv_test.go
  pkg/formatter/formatter.go
  pkg/formatter/formatter_internal_test.go
  pkg/formatter/table.go
  pkg/formatter/txt.go
  pkg/formatter/txt_test.go
  pkg/reporting/cookbooks.go
  pkg/reporting/cookbooks_test.go
Labels: Aspect: UX, Status: Adopted, Triage: Confirmed, Type: Enhancement
